server:
  port: 9018
security:
  oauth2:
    client:
      client-id: client #要与oauth_client_details表中的client_id一致
      client-secret: secret #要与oauth_client_details表中的client_secret一致
      access-token-uri: http://localhost:9001/oauth/token
      user-authorization-uri: http://localhost:9001/oauth/authorize
    resource:
      token-info-uri: http://localhost:9001/oauth/check_token
spring:
  application:
    name: pt-company-id
  devtools:
    restart:
      enabled: true #热部署生效
  freemarker:
    cache: false  #页面不加载缓存，修改即时生效
    #设置重启的目录
    #additional-paths: resources/**,static/**,templates/**
    #该目录下的内容修改不重启
    #exclude:  WEB-INFO/**
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pt-v2?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
