server:
  port: 9998

spring:
  application:
    name: pt-gateway
  cloud:
    gateway:
      locator:
        enabled: true
      routes:
        - id: pt-center
          uri: lb://pt-center
          predicates:
            - Path=/center/**
          filters:
            - StripPrefix= 1
        - id: pt-company-id
          uri: lb://pt-company-id
          predicates:
            - Path=/company_id/**
          filters:
            - StripPrefix= 1
        - id: pt-portal
          uri: lb://pt-portal
          predicates:
            - Path=/portal/**
          filters:
            - StripPrefix= 1
        # ???????
        - id: pt-auth
          uri: lb://pt-auth
          predicates:
            - Path=/auth/**
          filters:
            # ??????????
            - PasswordDecoderFilter
            - StripPrefix= 1
        # ???????
        - id: pt-dealer-proc
          uri: lb://pt-dealer-proc
          predicates:
            - Path=/proc/**
          filters:
            - StripPrefix= 1
        - id: pt-user
          uri: lb://pt-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix= 1
        - id: pt-dealer-prod
          uri: lb://pt-dealer-prod
          predicates:
            - Path=/prod/**
          filters:
            - StripPrefix= 1
        - id: pt-dealer-order
          uri: lb://pt-dealer-order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix= 1
        - id: pt-upload
          uri: lb://pt-upload
          predicates:
            - Path=/upload/**
          filters:
            - StripPrefix= 1
        - id: pt-manor
          uri: lb://pt-manor
          predicates:
            - Path=/manor/**
          filters:
            - StripPrefix= 1
        - id: pt-chat
          uri: lb://pt-chat
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix= 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true


security:
  encode:
    #16Î»
    key: '-www.cup.edu.cn-'
ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 1000
  ReadTimeout: 3500
