const getters = {
  sidebar: state => state.app.sidebar,
  size: state => state.app.size,
  device: state => state.app.device,
  visitedViews: state => state.tagsView.visitedViews,
  cachedViews: state => state.tagsView.cachedViews,
  access_token: state => state.user.access_token,
  avatar: state => state.user.avatar,
  user_name: state => state.user.user_name,
  user_id: state => state.user.user_id,
  nick_name: state =>state.user.nick_name,
  introduction: state => state.user.introduction,
  roles: state => state.user.roles,
  permissions: state => state.user.permissions,
  permission_routes: state => state.permission.routes,
  menu : state => state.user.menu,
  url : state => state.portal.url,
  company_id : state => state.portal.company_id,
  userList : state => state.chat.userList,
  emojis : state => state.chat.emojis,
  conversationsList: state => state.chat.conversationsList,
  selectedRoom: state => state.chat.selectedRoom,
  groupMemberMap: state => state.chat.groupMemberMap,
  searchedConversationList: state=>state.chat.conversationsList.filter(conversation =>conversation.chatName.includes(state.chat.searchText)),
}
export default getters
